In [61]:
%pip install numpy
import numpy

print("test")

Note: you may need to restart the kernel to use updated packages.


In [85]:
y = numpy.array( [[(1,2),(5,6)]], numpy.int32)
# Guardando enteros de 32 bit

X = numpy.array(['hola','hola', '1'])

X


array(['hola', 'hola', '1'], dtype='<U4')

In [63]:
y.dtype

dtype('int32')

In [64]:
y.shape

(1, 2, 2)

In [65]:
print(X)

['hola' 'hola' '1']


In [66]:
y = numpy.array([[1,2,3],[4,5,6]])

y.dtype

dtype('int32')

In [67]:
y[1,:2]

array([4, 5])

In [68]:
y = numpy.array([[1,2,3],[4,5,6]])

y.dtype


dtype('int32')

In [69]:
y = numpy.array([[1,2.0,3],[4,5,6]])

y.dtype


dtype('float64')

In [70]:
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]


In [71]:
# Extraction of elements

y[0,:2]

array([1., 2.])

In [72]:
# Extraction of elements


y[1,:2]

array([4., 5.])

In [73]:
# Extraction of elements


y[1,:3]

array([4., 5., 6.])

In [74]:
print(y)


[[1. 2. 3.]
 [4. 5. 6.]]


In [75]:
#To make a copy ([row,column])

a = y [:,1].copy()
print(a)

[2. 5.]


In [76]:
# Reassign value

y[0]=20
print(y)


[[20. 20. 20.]
 [ 4.  5.  6.]]


In [77]:
# Taking specific elements from the copy

y[0:3,0:3]

array([[20., 20., 20.],
       [ 4.,  5.,  6.]])

In [78]:
# Taking specific elements from the copy

y[0:2,0:2]

array([[20., 20.],
       [ 4.,  5.]])

In [79]:
# Taking specific elements from the copy

y[0:1,0:1]

array([[20.]])

In [80]:
# Taking specific elements from the copy

y[1:2,0:1]


array([[4.]])

In [81]:
print(y)

[[20. 20. 20.]
 [ 4.  5.  6.]]


In [82]:
# Taking specific elements from the copy

y[:1,0:1]


array([[20.]])

In [83]:
# Taking specific elements from the copy

y[:2,:2]


array([[20., 20.],
       [ 4.,  5.]])

In [84]:
# Taking specific elements from the copy
# ???

y[1:2,2:3]


array([[6.]])