In [25]:
%pip install numpy
import numpy

print("test")

Note: you may need to restart the kernel to use updated packages.
test



[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
y = numpy.array( [[(1,2),(5,6)]], numpy.int32)
# Guardando enteros de 32 bit

X = numpy.array(['hola','hola', '1'])

X


array(['hola', 'hola', '1'], dtype='<U4')

In [27]:
y.dtype

dtype('int32')

In [28]:
y.shape

(1, 2, 2)

In [29]:
print(X)

['hola' 'hola' '1']


In [30]:
y = numpy.array([[1,2,3],[4,5,6]])

y.dtype

dtype('int32')

In [31]:
y[1,:2]

array([4, 5])

In [32]:
y = numpy.array([[1,2,3],[4,5,6]])

y.dtype


dtype('int32')

In [33]:
y = numpy.array([[1,2.0,3],[4,5,6]])

y.dtype


dtype('float64')

In [34]:
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
# Extraction of elements

y[0,:2]

array([1., 2.])

In [36]:
# Extraction of elements


y[1,:2]

array([4., 5.])

In [37]:
# Extraction of elements


y[1,:3]

array([4., 5., 6.])

In [38]:
print(y)


[[1. 2. 3.]
 [4. 5. 6.]]


In [39]:
#To make a copy ([row,column])

a = y [:,1].copy()
print(a)

[2. 5.]


In [40]:
# Reassign value

y[0]=20
print(y)


[[20. 20. 20.]
 [ 4.  5.  6.]]


In [41]:
# Taking specific elements from the copy

y[0:3,0:3]

array([[20., 20., 20.],
       [ 4.,  5.,  6.]])

In [42]:
# Taking specific elements from the copy

y[0:2,0:2]

array([[20., 20.],
       [ 4.,  5.]])

In [43]:
# Taking specific elements from the copy

y[0:1,0:1]

array([[20.]])

In [44]:
# Taking specific elements from the copy

y[1:2,0:1]


array([[4.]])

In [45]:
print(y)

[[20. 20. 20.]
 [ 4.  5.  6.]]


In [46]:
# Taking specific elements from the copy

y[:1,0:1]


array([[20.]])

In [47]:
# Taking specific elements from the copy

y[:2,:2]


array([[20., 20.],
       [ 4.,  5.]])

In [48]:
# Taking specific elements from the copy
# ??

y[1:2,2:3]


array([[6.]])